name: Mission
favicon: null
layout_spectrum: 0.6473090471699834
typography_spectrum: 0.358330222312361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.801013839431107
  lightness: 0.958039270946756
  saturation: 0.4577434379607439
  rhythmicContrast: 0.42505339882336557
purpose: []
